name: Publish to PyPI
#
#on:
#  release:
#    types: [published]
on:
  push:
    branches:
      - pypi-package

permissions:
  id-token: write

jobs:
  publish:
    name: Publish
    environment: pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build and Publish
        run: |
          uv build
          uv publish --index testpypi